version: '3.4'

services:
  leaking-app:
    image: ${DOCKER_REGISTRY-}leakingapp
    ports:
        - 80:80
        - 443:443
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
        resources:
            limits:
                memory: 256mb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro